### PR TITLE
Tests for kue.js

### PR DESCRIPTION
**Pull request by tobalsgithub**
This PR creates unit tests for the `kue.js` file. We hope to create unit tests for the entire kue repo. 

Connects to #280 

@behrad, we can either create individual PRs for each file, or keep adding to this PR as we get more tests written. Either way, I wanted to get this in front of you as quickly as possible so you had a chance to give feedback.

### CODE REVIEW

**Comment by tobalsgithub** [comment]
Looks like some of the bdd tests are failing, but not sure that's related to what I did here. All the failures are the same: `jobs.client.connection_option` is undefined. Looks like it should be `jobs.client.options` instead. Want me to fix that?

**Comment by behrad** [comment]
Good stuff @tobalsgithub Can you check why tests are failing?

**Comment by tobalsgithub** [comment]
See my comment right before yours.

**Comment by tobalsgithub** [comment]
Actually, looks like `connection_options` instead of `connection_option` would work as well. Don't really understand how this was working before and is now breaking.

**Comment by tobalsgithub** [comment]
Went ahead and updated the tests to fix the connection issues

**Comment by behrad** [comment]
Strange!

:+1: @tobalsgithub

**Pull request merged**
