### PR TITLE
Skip feature

### PR DESCRIPTION
**Pull request by andrewtamura**
Would you be open to adding a `skip` feature like this? I can write all the tests

### CODE REVIEW

**Comment by behrad** [comment]
I think this will complicate user's app job management, why not to fail and let that job retry later !?
or event create a new job based on current...
Can't see whats behind this @andrewtamura

**Comment by andrewtamura** [comment]
I've read through the docs and code again and I think I see what you are saying.

If I have 100 jobs like this:
```
 queue.create('email', {
     title: 'welcome email for tj'
   , to: 'tj@learnboost.com'
   , template: 'welcome-email'
 }).attempts(5).backoff({type:'exponential'}).save();
```
and process them like this:
```
queue.process('email', 10, function(job, done){
    var err = new Error('Don't do the job, just fail it');
    done(err);
});
```
My 10 concurrent workers will take the first 10 jobs and fail them immediately. Then because the jobs have `attempts` and `backoff` set, they will not be `failed` but they will instead be `delayed` and my 10 workers will immediately process the next 10 jobs in the queue?

**Comment by behrad** [comment]
Yes.
`.attempts(5)` makes them to be queued/delayed again (=retry), and since you have not set a `delay` they will be queued immediately :)

**Comment by behrad** [comment]
not selected to be added to Kue for now.

**Pull request closed without merging**
