### PR TITLE
Fixing Job processing order without munging the job IDS

### PR DESCRIPTION
**Pull request by hockeytim11**
This is my attempt at fixing the FIFO issue.

I created an internal zid value that is used for zsets. This string value is in form: (id.length)id.

This allows for the ID to be parsed back out while maintaining the job order.

The length portion is fixed at 3 characters, which allow for ids to stay in order up to 999 digits long. This seemed sufficient to me, but is an upper limit. This could be easily increased if there is a need.

### CODE REVIEW

**Comment by hockeytim11** [comment]
I know there have been a couple fixes for this submitted, but I wanted one that didn't permanently mess up the job id. This should preserver a FIFO job order up to a 999 digit job id while presenting the normal expected job id to the user of the library.

I am happy to clean it up some if that would help get it merged.

**Comment by hockeytim11** [comment]
According to the docs for redis, INCR will max out at a 64bit signed integer: 9223372036854775807. So this method of job id sorting will outlast the redis server. A 2 digit length value would actually be sufficient.

**Comment by kulbirsaini** [comment]
Thanks for this. Looks good. I think it's a good bet to keep id length to two digits. A job id of more than 99 digits is a bit too far fetched in my opinion :-)

My suggestion is to use a `|` or `-` to separate `idLen` and `jobId`. That way you do save one character. Plus if you go for 2 digit length, then you save another character there. In a system with a million jobs, that's 2M characters removed from memory.

**Comment by hockeytim11** [comment]
Those seem like good suggestions. Changes have been pushed.

**Comment by hockeytim11** [comment]
Moved the stripFIFO and createFIFO calls to the client object so they can be updated in one place. Just like the getKey function.

**Comment by behrad** [comment]
will check this soon, thank you guys...

**Comment by behrad** [comment]
merged in 0.10.3

**Pull request closed without merging**
