### PR TITLE
Feature/time series states

### PR DESCRIPTION
**Pull request by mansona**
This tracks the time that a job changes state on a hourly granularity in a zset with key `'jobs:' + state + ':' + (Math.floor(Date.now() / 3600000) * 3600000)` where `(Math.floor(Date.now() / 3600000) * 3600000)` is just a timestamp that is a "floored hour"

This also provides a json api to access the time series data using the autoroute upgrade in this PR https://github.com/Automattic/kue/pull/792

There is a test that copies the same style as other JSON API tests to verify that it works. 

Let me know if you have any questions and I can go into a more full explanation.

### CODE REVIEW

**Comment by mansona** [comment]
This is *forked from https://github.com/Automattic/kue/pull/792* so it shouldn't be merged unless https://github.com/Automattic/kue/pull/792 is merged first. If https://github.com/Automattic/kue/pull/792 gets rejected I can undo the autoroute portion of this PR :+1:

**Comment by mansona** [comment]
Ok so I've made 2 changes

* I've changed the new API endpoints to follow [json:api](http://jsonapi.org/) because I'm consuming them in the kue-ui alternative ui
* I've moved the new route files into a `v2` api because they are so significantly different to the old APIs. This also incidentally shows one of my other justifications of using `express-autoroute` https://github.com/Automattic/kue/pull/792 i.e. you just need to move a route file into a `v2` folder and it gets the `v2` prefix

You can see my kue-ui PR that actually makes use of the new endpoints here https://github.com/StreetHub/kue-ui/pull/21 or you can just have a look at the small video I created to illustrate my point: 

[kue-ui demo](http://www.youtube.com/watch?v=MLy5oz6ZKrc)

**Comment by behrad** [comment]
Thank you for your efforts @mansona 
I'll review this ASAP

**Comment by mansona** [comment]
hey @behrad thanks :smile: I really appreciate you taking the time, if you have anything that you think I could improve on just fire away! I'm not afraid of a bit of criticism :smirk: 

I've just pushed a quick update there that adds error text to the job if it exists :+1:

**Comment by mansona** [comment]
Hey Folks, any more thoughts on this? 

I have been using this in production for quite some time now and it works beautifully. It has been a real help to figure out issues with the jobs on live. 

Let me know if there is anything you would need from me to get this merged, if you would like a discussion about it we could arrange a call if you like.

**Comment by behrad** [comment]
I need time to review the code and see how can we merge it in beautifully without mess, Thank you for the nice work @mansona .

**Comment by mansona** [comment]
@behrad well if you want help on the merge strategy just let me know. This is the first step of exposing some of the data required via JSON-API and I have a few ideas on how to maintain the API and roll out new features 👍  

Not trying to rush you, I know you're probably mad busy 😄

**Comment by behrad** [comment]
Before merging this @mansona , Can we omit `.editorconfig` from the commit and add tests for new API?

**Comment by mansona** [comment]
hey @behrad sorry I missed your comment. I have removed editorconfig for now, we can discuss adding it back later with your own settings if you like. 

re: the tests I'm really not sure how to progress with that. I have a particular way that I produce API tests but it won't be in keeping with the style of your current tests and I also don't know how to best setup fixtures (real kue objects or just mocks/stubs etc) to make them a valid test. 

I would propose that we merge this PR because it currently doesn't break any of the current functionality and setup a meta issue for discussion of the new API testing. Either that or we could arrange a Skype if you were interested. 

How does that sound?

**Comment by mansona** [comment]
Hey folks, just letting you know I've synced this PR with master. I noticed it could not longer be automatically merged. 👍

**Comment by mansona** [comment]
Hey Folks, Just letting you know that I've taken over the [Kue-UI repo](https://github.com/stonecircle/kue-ui) and I'm currently fielding quite a few requests from end users looking for progress on this PR. I know you're probably super busy but could we put a date in the diary to have a Skype call, maybe in September to get this moving? 

If there is anything I can do to make this any easier please let me know 👍

**Comment by mansona** [comment]
hey @behrad I think you may have closed this as a typo? can you re-open this PR so we know it's still an ongoing concern?

**Comment by behrad** [comment]
I'm trying to freeze 0.11.x @mansona and your great work is more than what I'm ready to merge to 0.11
What refactoring your changes after 1.0 is out? I will separate web API as another module, and we may have this there.

**Comment by mansona** [comment]
Cool sounds like a good plan forward, would you like me to help with just separating the current Web API into a module (without any changes) and we can the create a new branch off that?

**Comment by behrad** [comment]
Thats great, we can plan for a clean HTTP API (may be also socket API) on top of which a UI can be written in another new module.
Are you ok with a long term support on that module?

**Comment by mansona** [comment]
well we should probably have a skype conversation about these plans, essentially I've taken over https://github.com/stonecircle/kue-ui which is already a "UI in a separate module". 

In principle I am happy to maintain the API module because I'm already maintaining something that will be consuming that API.

**Comment by behrad** [comment]
Good,
We can 
1) create a new HTTP/Socket API module
2) Refactor https://github.com/stonecircle/kue-ui to use 1
2) Drop current kue web ui in favor of https://github.com/stonecircle/kue-ui

Have you commit right to https://github.com/stonecircle/kue-ui ? It seems no active recently.

**Comment by mansona** [comment]
great! that sounds like a brilliant plan 👍 

Essentially I "own" kue-ui right now (I'm the director of Stone Circle). Because of my work on this PR: https://github.com/stonecircle/kue-ui/pull/21 which depends on the JSON:API work above the previous maintainers ended up handing it over to me. 

The reason why there has been no activity lately is because that PR I linked to is essentially a "rewrite" of the kue-ui so that it is now just an ember app instead of a proxy server that hosts the ember app. I've already been working to make this setup more modular 😉  

Now we just need to get the ball rolling on your HTTP module idea. Where is best to organise this? Should I create a new meta issue and we can keep our discussions there?

**Pull request closed without merging**
