### PR TITLE
start using autoroute to clean up routes

### PR DESCRIPTION
**Pull request by mansona**
I'm just about to create a new PR to add a new route (or extend an existing route) and I wanted to make it easier for other users to extend routes in the future by cleaning up the file that defines the API routes using https://github.com/stonecircle/express-autoroute

The intention would be to split the https://github.com/Automattic/kue/blob/master/lib/http/routes/json.js file into the corresponding route files but I didn't want to go further into this implementation without running it by you. 

Let me know if you want to discuss it any further or if you have any questions.

### CODE REVIEW

**Comment by behrad** [comment]
Looks cleaner @mansona Thank you.
I hadn't heart about `autoroute`, is it a mature, active project?
Can you convince me on the value of this PR to add such dependency?

**Comment by mansona** [comment]
Yea sure. It's quite a mature project and we have been using it in production for the last 2 years. It is also the basis of https://github.com/Blooie/express-autoroute-json which auto generates routes for MongoDB objects (so doesn't really apply here) which has also been in production for us for roughly a year. 

The main reason why I think this is a valuable addition is to allow new developers to quickly and easily see get up to speed with your code base to either add new functionality or fix/improve existing functionality. This PR is really just dealing with the routes files but I'm just about to create another PR that *adds* functionality and a new route. You will be able to see how it makes it simpler to implement new routes now when I add the next PR (in 2 mins)

**Comment by mansona** [comment]
So the true justification for the use of Autoroute is the updates that I made to the stats route file in the other PR https://github.com/Automattic/kue/pull/794/files#diff-fba636302699c364dfcbbecd70ea436dR1

The key advantage is that there is a better cognitive connection between the implementation of the route and where it exists in the file system. 

Let me know if you want me to explain this any more :+1:

**Comment by behrad** [comment]
Should I close this in favor of #794?

**Comment by mansona** [comment]
Hey @behrad yes I think that's probably a good idea as the autoroute stuff is included in the other PR

**Pull request closed without merging**
