### PR TITLE
Adding support for multi-type workers.

### PR DESCRIPTION
**Pull request by hockeytim11**
BLPOP is capable of handling multiple queues. So all that is needed to
process multiple queues with one worker is to call queue.process([array
of types],fn).

Kue will then work through the types in the array in order. See BLPOP
for more info.

### CODE REVIEW

**Comment by behrad** [comment]
I'll be moving away from BLPOP in next Kue version

**Comment by hockeytim11** [comment]
I assume you are looking at BRPOPLPUSH. Unfortunately, that command doesn't support multiple lists like BLPOP does. I understand why (atomic operations are good), but do you think there will be an opportunity to have multi-type workers in the new version as well? I'm not sure how to do that with BRPOPLPUSH.

**Comment by behrad** [comment]
this is actually a trade-off between feature and robustness, which I believe the later is more important to this module!

**Comment by gebrits** [comment]
hi @behrad, what are your ideas on supporting multiple queues in the same process? Any roadmap I can read up?

**Comment by behrad** [comment]
> what are your ideas on supporting multiple queues in the same process?

Are you talking about multiple Kue object instances (instead of current Singleton)? I'm not sure If I understand what you mean.

**Comment by gebrits** [comment]
@behrad, yep that's what I mean. 

I'd love to have multiple kue-object instances, to be able to have more fine-grained control over concurrency, etc.

**Comment by behrad** [comment]
I was planing to do this in Kue 1.0 However I was busy mid 2015...
I'd help and a PR is welcome

**Comment by gebrits** [comment]
OK cool. I'll let you know if I attempt to take a crack at it.

**Pull request closed without merging**
