### PR TITLE
Update job.js Emit logs back to master

### PR DESCRIPTION
**Pull request by FLYBYME**
Emit logs back to master

### CODE REVIEW

**Comment by behrad** [comment]
there's another issue/PR that adds another parameter into `progress` for both sides to interact between job processing...
I want to know why is this necessary and how it relates to the other!?

**Comment by FLYBYME** [comment]
I use kue as a build server. I need the logs send back to the creator so I can log them back to the user. I dont think it has much to do with the `progress` event.

**Comment by behrad** [comment]
are they really `logs` or can they be just aggregated job `result`!?

**Comment by FLYBYME** [comment]
If it take 20 minutes to do a job and you dont want to wait? Anyway you can pull the logs from redis after the job is done.

I think this is very useful. This is more of a real-time thing.

**Comment by behrad** [comment]
I still think you can do it via progress... I'm not convinced that we can pollute the redis pub/sub with log messages, this can have performance impacts on heavy logging apps, can't it?

**Pull request closed without merging**
