### PR TITLE
Add socket.io API

### PR DESCRIPTION
**Pull request by jackmasa**
Add socket.io API

### CODE REVIEW

**Comment by behrad** [comment]
Can this be also used in web panel instead of current 1ms polling?

**Comment by jackmasa** [comment]
@behrad it's "Socket.IO JSON API" :)

**Comment by behrad** [comment]
I see, and why not use it in the default kue express web app?

**Comment by jackmasa** [comment]
@behrad  good idea :smiley:

**Comment by jackmasa** [comment]
@behrad How to deal with this situation :
```javascript
app.use(kue.app);
//or
var server = require('https').createServer({
	  key: fs.readFileSync('./privatekey.pem'),
    cert: fs.readFileSync('./certificate.pem')
},kue.app);
```

**Comment by behrad** [comment]
Didn't get your point @jackmasa !?

**Comment by jackmasa** [comment]
@behrad 

Socket.io + Express :
```
var app = require('express').createServer();
var io = require('socket.io')(app);
//or
var server = require('https').createServer({
      key: fs.readFileSync('./privatekey.pem'),
    cert: fs.readFileSync('./certificate.pem')
});
io.attach(server);
```
But in many cases this is the use kue:
```
app.use(kue.app);
//or
var server = require('https').createServer({
      key: fs.readFileSync('./privatekey.pem'),
    cert: fs.readFileSync('./certificate.pem')
},kue.app);
```
Do you have any good way to get socket.io attach the default kue express?

**Comment by qrpike** [comment]
Any news on this?

**Comment by behrad** [comment]
I think socket API helps only on more scalable Job creation/management, otherwise one could easily wrap existing HTTP API inside their own socket implementation.

We should separate HTTP API into another module from kue 1.0 and add socket.io there

**Pull request closed without merging**
