### PR TITLE
Unique Job

### PR DESCRIPTION
**Pull request by EricMcRay**
You can make jobs unique by a field. Works nice with `removeOnComplete`

### CODE REVIEW

**Comment by dan335** [comment]
:+1:

**Comment by gabrielcsapo** [comment]
👍

**Comment by posgarou** [comment]
👍   Is there anything I can do to help it get merged?

**Comment by behrad** [comment]
Main issue for this PR is that this is a bit old and I've removed warlock from v1 branch.
Can someone check if this can be translated to v1 branch?

**Comment by nrempel** [comment]
Will try to take a look at this when I have time since this would be really useful!

**Comment by nrempel** [comment]
@behrad since there seems to be a fair bit of work left to reach version 1, would you consider merging this into the current version?

**Comment by ross-nordstrom** [comment]
This seems to have stagnated... I'm going to try to update this with the current version of Kue - #1034

**Comment by thierryskoda** [comment]
@ross-nordstrom Any news regarding this? I saw your PR. It's awesome! I was wondering if it was possible to merge it into master?

Thank you!

**Comment by ross-nordstrom** [comment]
@thierryskoda I never got a review on that PR.  When I played with the changes in my app, I found that it didn't work as robustly as I would like.  I *think* I remember having issues where you couldn't consistently re-enqueue a Unique Job.

**Pull request closed without merging**
