### PR TITLE
Modern Node.js versions support

### PR DESCRIPTION
**Pull request by kerimdzhanov**
Node.js currently supports **v4.2.6 LTS** and *v5.5.0 Latest Stable*, let's make tests run against them in Travis.

### CODE REVIEW

**Comment by behrad** [comment]
Something is failing @kerimdzhanov ?

Can you also add 0.12?

**Comment by kerimdzhanov** [comment]
On my local machine all versions was success, i will check.

Regarding to the v0.12, I also think it should be added :+1:.

**Comment by kerimdzhanov** [comment]
Something strange with `Queue#shutdown`, sometimes tests passed sometimes not.

Take a look at my build: https://travis-ci.org/kerimdzhanov/kue

**Comment by kerimdzhanov** [comment]
This error happens very rare and not depending on the Node.js version.
I'm trying to catch it...

**Comment by kerimdzhanov** [comment]
I've done with catching the errors. As I already wrote, they not depending on the Node.js version, so I sent it in another PR #813 (I suggest to merge it first).

Regarding to this PR, you can "Restart" the build on Travis and it most likely will be successful.

**Pull request merged**
