### PR TITLE
Fixed invalid CSS, bumped stylus

### PR DESCRIPTION
**Pull request by nyurik**
"highlight-color += 10%" in context-menu.styl produces
an invalid color entry in CSS

### CODE REVIEW

**Comment by nyurik** [comment]
@behrad, adding the main.css to the distribution solves the problem for the secure servers - in our case, Wikimedia servers are well secured, and their settings do not allow on-the-fly code modification - that's why I noticed this issue.  In general case, I don't think stylus should generate code dynamically at all - its not a good practice to rely on it - code should stay static.  As for injection - its impossible to "fix it" via the code here, it can only be solved by doing what we already did - by setting proper file permissions on the production server. This way if someone discovers a bug in our code and uses it to try to write a local file, they will fail because of the file permissions.

**Comment by nyurik** [comment]
P.S. I do notice that once in a while the style does not load even though it is there, and I have to refresh. I don't know what's causing it, might be some other stale cache issue.

**Comment by behrad** [comment]
Kue is updated, and there are conflicts :)
Can you rebase this PR @nyurik ?

**Comment by nyurik** [comment]
@behrad , i rebased it -- see #755

**Pull request closed without merging**
