### PR TITLE
Add `Job#suppressAttempts()`, closes #810

### LINKED ISSUE #810: Controlling failure attempts "on the fly"
Hi there,

As I understand, failure attempts can be controlled only using the `Job#attempts` method, and any failed job retries _x_ times.

How about controlling that retries from a `queue.process` function? There are many error cases in processing jobs that shouldn't be retried. e.g. validation errors.

I would like to fail a job without retrying if one of the required job parameters is missing or invalid.
Or, if it's a kind of network error or database connection failure I would like to be able to retry current job.

Is there more elegant way to control the failure attempts than like this:

``` js
queue.process('email', function (job, done) {
  if (!isValidEmail(job.data.email)) {
    return done(null, { error: new Error('invalid email address') });
  }

  sendEmail(job.data, function (err) {
    if (err) { // e.g. temporary network error
      return done(err);
    }

    done();
  });
});
```

Instead, I would like to have something like:

``` js
queue.process('email', function (job, done) {
  if (!isValidEmail(job.data.email)) {
    job.finalize(); // that fails the job immediately without retrying
    return done(new Error('invalid email address'));
  }

  sendEmail(job.data, function (err) {
    if (err) { // e.g. temporary network error
      return done(err);  // without finalization, will be retried
    }

    done();
  });
});
```

Thanks in advance!

### PR DESCRIPTION
**Pull request by kerimdzhanov**
This gives the ability to suppress subsequent failure attempts within the job processing function.

Example usage:

```js
queue.process('email', function (job, done) {
  if (!isValidEmail(job.data.email)) {
    job.suppressAttempts(function () { // make a note that you need to call `done` after suppress calls back
      return done(new Error('invalid email address'));
    });
  }

  sendEmail(job.data, function (err) {
    if (err) { // e.g. temporary network error
      return done(err);  // without suppressing will be retried
    }

    done();
  });
});
```

Closes #810

### CODE REVIEW

**Comment by behrad** [comment]
Everything looks OK, we only need a documentation section for "aborting jobs on critical errors"...

You can also mention to updating documentation in CONTRIBUTING doc... ;)

**Comment by kerimdzhanov** [comment]
Yep, _CONTRIBUTING_ will be another PR.

**Comment by kerimdzhanov** [comment]
I began using this in my project, and it still not makes me happy :(

First of all, I don't like the _two words_ name of the function.
Maybe it's better to drop _attempts_ and leave just `job.suppress()`?

The second thing – is that I'm required to call `done(err)` inside the suppress' callback.
Additionaly, this callback also can be called with it's own error (if `job#save` failures).

And the last (but not least) is that in worker functions there are much more job completion branches with suppressing reattempts than not.

What do you think about it?

**Comment by kerimdzhanov** [comment]
Here is an example:

```js
queue.process('processing:exec_transaction', (job, done) => {
  var transaction = job.data.transaction;

  if (!transaction) {
    var err = new Error('missing `job.data.transaction`');
    return job.suppressAttempts((e) => {
      if (e) {
        console.log(e, 'failed to suppress job failure attempts'); // >>>
        return done(null, { error: err }); // complete the job without an error to prevent subsequent calls
      }

      done(err);
    });
  }

  var progress = 0;
  processing.exec(transaction)
    .on('statechange', (status) => {
      job.progress((progress++), 100, { status: status });
    })
    .on('failure', (err) => {
      done(err); // this is the only place when we want to reattempt
    })
    .on('complete', (err) => { // transaction completed,
      if (err) { // but with an error,
        return job.suppressAttempts((e) => { // so we shouldn't reattempt it again
          if (e) {
            console.log(e, 'failed to suppress job failure attempts'); // >>>
            return done(null, { error: err }); // complete the job without an error to prevent subsequent calls
          }

          done(err);
        });
      }

      done();
    });
});
```

**Comment by behrad** [comment]
`job.attempts( 0, function(){ done(origJobError) });` is my thought after your last arguments

**Comment by kerimdzhanov** [comment]
Agreed.

**Pull request closed without merging**
