### PR TITLE
Remove old unlock call

### PR DESCRIPTION
**Pull request by schnie**
I'm dumb.  When I reverted some commits yesterday to clean up the PR commit, I only added the new code, and forgot to remove the old unlock call!  Sorry about that!

### CODE REVIEW

**Comment by behrad** [comment]
and why did I missed that when was reviewing yours? :(
Thank you

**Comment by schnie** [comment]
Oh well.  Thanks for being so responsive getting this fixed!  Are you planning on another patch release soon?

**Comment by behrad** [comment]
`0.9.3` is on npm.

**Comment by schnie** [comment]
Awesome!  Thanks again!

**Pull request merged**
